{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: handoff
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.domain | quote }}
        - {{ printf "*.%s" .Values.domain | quote }}
        - {{ printf "api.%s" .Values.domain | quote }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ printf "api.%s" .Values.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: handoff-api
                port:
                  number: 80
    - host: {{ printf "*.%s" .Values.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: handoff-web
                port:
                  number: 80
    - host: {{ .Values.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: handoff-web
                port:
                  number: 80
{{- end }}
